services:
  - name: nexus-app
    type: web
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./AngularApp4/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: MongoDb__DatabaseName
        value: nexus
      - key: Jwt__Issuer
        value: HospitalManagementSystem
      - key: Jwt__Audience
        value: HospitalManagementSystem.Client
      - key: Jwt__Key
        sync: false
      - key: Jwt__ExpiresInMinutes
        value: "120"
